# SwiftLint Configuration for OMOMoney
# This file configures SwiftLint to enforce code quality standards

# MARK: - Disabled Rules
disabled_rules:
  # Temporarily disable some rules that might conflict with current codebase
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity

# MARK: - Enabled Rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# MARK: - Rule Configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

# MARK: - Custom Rules
custom_rules:
  # Ensure @MainActor is used for UI-related code
  main_actor_usage:
    name: "Main Actor Usage"
    regex: 'class.*ViewModel.*\{'
    message: "ViewModels should use @MainActor for UI thread safety"
    severity: warning
    
  # Ensure async/await is used consistently
  async_usage:
    name: "Async Usage"
    regex: 'Task\s*\{'
    message: "Consider using async/await instead of Task blocks where possible"
    severity: warning

# MARK: - Excluded Paths
excluded:
  - Carthage
  - Pods
  - OMOMoney.xcodeproj
  - OMOMoney.xcworkspace
  - .build
  - .swiftpm
  - OMOMoneyTests
  - OMOMoneyUITests
  - OMOMoneyPerformanceTests

# MARK: - Analyzer Rules
analyzer_rules:
  - unused_declaration
  - unused_import
  - unused_private_declaration

# MARK: - Reporter
reporter: "github-actions-logging"

# MARK: - Cache Path
cache_path: .swiftlint_cache
